<head>

<?php
	echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jstree/style.min.css');
	echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-2.1.1.js', 'text/javascript');
	echo $this->headScript()->appendFile($this->baseUrl() . '/js/jstree.min.js', 'text/javascript');
?>

<script>
$(function () {
	
	$('#jstree').jstree({ 'core' : {
		'data' : [
			  		<?php echo $this->fileTreeString; ?>
		],
	    "plugins" : [ "sort" ]
	}});

	$(document).on('click', "a", function () {
		var href = $(this).attr('href');
		
		if(href != '#' || href != '' )
		{
			var rootPath = $('#SYSTEM_ROOT_PATH').val();

			$.ajax({
		        url: rootPath + "joetests/ajaxgeshi",
		        type: 'POST',
		        async: 'false',
				data: { filePath: href},
		        success: function(text_data)
				{
					$('#doc_content').html(text_data);
		        },
		        error: function(request, textStatus, errorThrown)
				{
		            var message = (request.status == 403) ? request.responseText : message;
		            alert("Error ajax: - " + message);
		        }
		    });
		}
	});
});
</script>
</head>

<body>

<h2>JsTree & GeShi libraries test</h2>
<div id="jstree">    
</div>

<h2>Document content</h2>
<div id="doc_content">    
</div>