<head>

<?php
	echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jstree/style.min.css');
	echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-2.1.1.js', 'text/javascript');
	echo $this->headScript()->appendFile($this->baseUrl() . '/js/jstree.min.js', 'text/javascript');
?>

<script>
$(function () {
	$('#jstree').jstree();

    // Bind to events triggered on the tree
    $('#jstree').on("changed.jstree", function (e, data) {
        console.log(data.selected);
    });

    $('button').on('click', function () {
        $('#jstree').jstree(true).select_node('child_node_1');
        $('#jstree').jstree('select_node', 'child_node_1');
        $.jstree.reference('#jstree').select_node('child_node_1');
    });
});
</script>
</head>

<body>

<h2>JsTree library test</h2>

  <div id="jstree">
    <!-- in this example the tree is populated from inline HTML -->
    <ul>
      <li>Root node 1
        <ul>
          <li id="child_node_1">Child node 1</li>
          <li>Child node 2</li>
        </ul>
      </li>
      <li>Root node 2</li>
    </ul>
  </div>
  <button>demo button</button>

