<div id="intro">
    
  <div class="inner">
      
    <div class="wrap clearFix">
            <a href='<?php echo $this->url(
					array(
						'controller' => 'user',
						'action'     => 'add'
                                            ), 'default', true) ?>' class="button">Registrar</a>   
      <a href='<?php echo $this->url(
					array(
						'controller' => 'user',
						'action'     => 'login'
                                            ), 'default', true) ?>' class="button">Ingresar</a>
      <h1>control de versiones <strong>Supay</strong></h1>
      <p>Sistema de control de versiones, basado en git</p>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  </div>
</div>
</div>