<?php 
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Supay');

echo $this->doctype();

$session = new Zend_Session_Namespace('systemSession');

?>
<!DOCTYPE html>
<html>
<head>
        <?php echo $this->headTitle(); 
        echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/main.css');
        echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/print.css', 'supay');       	      
        echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui-1.8.13.custom.min.js', 'text/javascript');
        
        echo "<input type='hidden' id='SYSTEM_ROOT_PATH' value='http://$_SERVER[HTTP_HOST]" . $this->baseUrl() ."/'/>";
        ?>
</head>

<header class="clearFix">
    <div class="wrap">
    <hr>
    <nav>
      <div id="nav">
        <ul>
          <li class="active"> <a href="#">Inicio</a> </li>
          <li> <a href="<?php echo $this->url(
					array(
						'controller' => 'user',
						'action'     => 'login'
					), 'default', true) ?>">Ingresar</a> </li>
          <li> <a href="<?php echo $this->url(
					array(
						'controller' => 'user',
						'action'     => 'add'
					), 'default', true) ?>">Registrarse</a> </li>
          <li> <a href="#">Ayuda</a> </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

<?php echo $this->layout()->content ?>

<footer class="clearFix">
  <div class="wrap clearFix">
    <p class="floatRight"> Universidad Mayor de San Simon; 2012 <a href="#">www.umss.edu.bo</a> &ndash; Sociedad Cientifica de Estudiantes de Sistemas e Informatica<br>
      Template by <a target="_blank" href="http://www.templatestar.net">Templatestar</a> &amp; <a target="_blank" href="http://www.os-templates.com/">OS Templates</a></p>
    <p class="socialIcons"> <a href="#" class="rss">RSS</a> <a href="#" class="facebook">Facebook</a> <a href="#" class="twitter">Twitter</a> </p>
  </div>
</footer>
</body>
</html>
