<div id="content">
  <div class="wrap clearFix">
<h2>Detalle de usuario:</h2>

<a href='<?php echo $this->url(
					array(
						'controller' => 'user',
						'action'     => 'index'
					), 'default', true) ?>'>Listado de usuarios</a>


<table border='1'>
	<tr>
		<th>Usuario:</th>
		<td><?php echo $this->user->getUsername(); ?></td>
	</tr>
        <tr>
            <th>Nombre:</th>
            <td><?php echo $this->user->getName(); ?></td>
        </tr>
	<tr>
		<th>Email:</th>
		<td><?php echo $this->user->getEmail(); ?></td>
	</tr>
</table>
  </div>
</div>