<?php echo $this->infoMenu(); ?>
<div id="content">
  <div class="wrap clearFix">
      <?php echo $this->userMenu();  ?>
      <br />
      <h2>Mis Proyectos</h2>
      <table class="col">
      	<thead>
      		<tr>
      			<th>Numero</th>
      			<th>Nombre</th>
      			<th>Descripcion</th>
      			<th>Acciones</th>
      		</tr>
      	</thead>
      	<?php
      		if($this->allPermissions){
      		foreach($this->allPermissions as $permission) {
      			$project = $permission->getProject();
      	?>
      	<tr>
      		<td><?php echo $project->getId(); ?></td>
      		<td><a href='<?php echo $this->url(array('controller' => '',
										 		 'action'     => '',
												 'id'     	  => $project->getId(),
										), 'default', true) . "'>".  $project->getName(); ?></a></td>
      		<td><?php echo $project->getDescription(); ?></td>
      		<td>aqui vienen las acciones</td>
      	</tr>      	
      	<?php  } } //end foreach ?>
      </table>
  </div>
</div>