<?php echo $this->infoMenu(); ?>
<div id="content">
  <div class="wrap clearFix">
      <?php echo $this->userMenu();  ?>
      <br />
      <h2>Mis Proyectos</h2>
      <table class="col">
      	<thead>
      		<tr>
      			<th>Numero</th>
      			<th>Nombre</th>
      			<th>Descripcion</th>
      			<th>Acciones</th>
      		</tr>
      	</thead>
      	<?php 
      		foreach($this->projects as $permission) {
               if($permission->getOwner()->getId() == $this->id) {

      	?>
      	<tr>
      		<td><?php echo $permission->getId(); ?></td>
      		<td><a href='<?php echo $this->url(array('controller' => 'branch',
										 		 'action'     => 'index',
												 'id'     	  => $permission->getId(),
										), 'default', true) . "'>".  $permission->getName(); ?></a></td>
      		<td><?php echo $permission->getDescription(); ?></td>
      		<td>aqui vienen las acciones</td>
      	</tr>      	
      	<?php  }}  //end foreach ?>
      </table>
  </div>
</div>